### ISSUE TITLE
Story mapping/ Refinamento dos cards

### ISSUE THREAD

**Issue by giordanasousa** [FeliciLab/RegistroCOVID#100]
Nós nos reunimos para realizar o Story Mapping do primeiro MVP, ou seja, pegamos as funcionalidades do primeiro MVP e mapeamos os títulos das histórias que devem ser escritas (é importante salientar que nada é escrito em pedra); Após o history mapping, iniciamos o refinamento das histórias, para entender o que faz sentido entrar em cada história e organizar nosso backlog.

- Story mapping - User Story Mapping é um mapa que organiza as histórias de usuário em um modelo que ajuda a compreender a funcionalidade do sistema, a identificar falhas no seu backlog, e a, efetivamente, planejar releases que oferecem valor aos usuários e ao negócio a cada versão.

- https://jamboard.google.com/d/1C9eJqTaRrOjA4xQ9qXvsU9r8_MdvFXU0n7Lq7exjBww/edit?usp=sharing

**Comment by victorMagalhaesPacheco** [comment]
https://www.google.com
